# DOCUMENTATION ONLY — DO NOT REQUIRE.
# Stubs for the elementwise rounding monops generated by
# ext/mkkernel.rb (MkKernel.monop :round / :frac).  These generated
# kernels carry no C docstring, so the documentation lives here.
#
# Style note (deviation): the canonical group list in STYLE.md has no
# elementwise-math bucket, so this file opens `Elementwise math` for the
# rounding family.  See yard-stubs/README.md and yard-stubs/STYLE.md.

class CArray
  # @!group Elementwise math

  # @overload round
  #   Returns a new array with each element rounded to the nearest
  #   integer value, half rounded away from zero (`2.5` -> `3.0`,
  #   `-2.5` -> `-3.0`).  The result keeps `self`'s `data_type`.
  #
  #   Integer arrays are returned unchanged.  For a `:float64` /
  #   `:float32` array the value stays floating-point (e.g. `1.4` ->
  #   `1.0`); a `NaN` element is passed through as `NaN`, and `-0.0`
  #   keeps its sign.  Masked elements stay masked.  An `:object`
  #   array delegates to each element's `#round`.
  #   @return [CArray] same `data_type` as `self`.
  def round; end

  # @overload frac
  #   Returns a new array of the fractional part of each element:
  #   `self - self.truncated_toward_zero`, so the result keeps the
  #   sign of the input (`1.25` -> `0.25`, `-1.25` -> `-0.25`).  The
  #   result keeps `self`'s `data_type`.
  #
  #   Integer arrays yield all zeros.  For a floating-point array a
  #   `NaN` element is passed through as `NaN`, and `±0.0` keeps its
  #   sign.  Masked elements stay masked.  An `:object` array
  #   delegates to each element's `#frac`.
  #   @return [CArray] same `data_type` as `self`.
  def frac; end

  # @!endgroup
end
