# DOCUMENTATION ONLY — DO NOT REQUIRE.
# Stubs for the elementwise arithmetic generated by ext/mkkernel.rb --
# the division and modulo binops and the rounding monops.  These
# generated kernels carry no C docstring, so the documentation lives
# here.  See yard-stubs/README.md and yard-stubs/STYLE.md.

class CArray
  # @!group Elementwise math

  # @overload /(other)
  #   Returns the element-wise quotient of `self` and `other`.
  #
  #   Integer division floors toward negative infinity, so that
  #   `(a / b) * b + a % b == a` holds for every combination of signs
  #   -- the same convention as Ruby's `Integer#/`. Float and complex
  #   division is true division, as Ruby's `Float#/` is, so that
  #   identity is an integer one. Boolean arrays participate as their
  #   0/1 storage. Masked elements stay masked, and a masked cell is
  #   never divided.
  #   @param other [CArray, Numeric] divisor, broadcast to `self.shape`.
  #   @return [CArray] result of the promoted `data_type` of the two
  #     operands.
  #   @raise [ZeroDivisionError] when an integer divisor is `0`. Float
  #     division returns `Infinity` or `NaN` instead.
  #   @example
  #     CA_INT32([-7, -1, 7]) / 3      # => [ -3, -1, 2 ]
  #     CA_DOUBLE([-7.0]) / 3.0        # => [ -2.3333333333333335 ]
  def /(other); end

  # @overload div(other)
  #   Alias of {#/}.
  #   @param other [CArray, Numeric] divisor.
  #   @return [CArray]
  def div(other); end

  # @overload div!(other)
  #   Divides `self` by `other` in place, keeping `self`'s `data_type`.
  #   @param other [CArray, Numeric] divisor.
  #   @return [self]
  def div!(other); end

  # @overload %(other)
  #   Returns the element-wise remainder of `self` divided by `other`,
  #   carrying the sign of the divisor.
  #
  #   This is the floored modulo, the pair of the floored `/` above and
  #   the same convention as Ruby's `%`: `-7 % 3` is `2`, and `7 % -3`
  #   is `-2`. A float remainder of zero takes the divisor's sign, so
  #   the rule holds without exception. For the truncated form that C
  #   gives -- the sign of the dividend -- use {#fmod}. Complex arrays
  #   have no modulo. Masked elements stay masked.
  #   @param other [CArray, Numeric] divisor, broadcast to `self.shape`.
  #   @return [CArray] result of the promoted `data_type` of the two
  #     operands.
  #   @raise [ZeroDivisionError] when an integer divisor is `0`. A float
  #     divisor of `0.0` yields `NaN`.
  #   @raise [CArray::DataTypeError] for a complex array.
  #   @example
  #     CA_INT32([-7, -1, 7]) % 3      # => [ 2, 2, 1 ]
  #     CA_INT32([7]) % -3             # => [ -2 ]
  #     CA_DOUBLE([-0.4]) % 1.0        # => [ 0.6 ]
  def %(other); end

  # @overload mod(other)
  #   Alias of {#%}.
  #   @param other [CArray, Numeric] divisor.
  #   @return [CArray]
  def mod(other); end

  # @overload mod!(other)
  #   Replaces `self` with the remainder in place, keeping `self`'s
  #   `data_type`.
  #   @param other [CArray, Numeric] divisor.
  #   @return [self]
  def mod!(other); end

  # @overload fmod(other)
  #   Returns the element-wise truncated remainder of `self` divided by
  #   `other`, carrying the sign of the dividend.
  #
  #   This is C's `fmod` and `%`: the quotient is truncated toward zero
  #   rather than floored, so `fmod(-7, 3)` is `-1` where `-7 % 3` is
  #   `2`. Integer arrays are accepted as well as floats. Complex
  #   arrays have no remainder. An `:object` array delegates to each
  #   element's `#remainder`, so an Integer element yields an Integer.
  #   Masked elements stay masked.
  #   @param other [CArray, Numeric] divisor, broadcast to `self.shape`.
  #   @return [CArray] result of the promoted `data_type` of the two
  #     operands.
  #   @raise [ZeroDivisionError] when an integer divisor is `0`. A float
  #     divisor of `0.0` yields `NaN`.
  #   @raise [CArray::DataTypeError] for a complex array.
  #   @example
  #     CA_INT32([-7, -1, 7]).fmod(3)  # => [ -1, -1, 1 ]
  #     CA_DOUBLE([-0.4]).fmod(1.0)    # => [ -0.4 ]
  def fmod(other); end

  # @overload fmod!(other)
  #   Replaces `self` with the truncated remainder in place, keeping
  #   `self`'s `data_type`.
  #   @param other [CArray, Numeric] divisor.
  #   @return [self]
  def fmod!(other); end

  # @overload round
  #   Returns a new array with each element rounded to the nearest
  #   integer value, half rounded away from zero (`2.5` -> `3.0`,
  #   `-2.5` -> `-3.0`).  The result keeps `self`'s `data_type`.
  #
  #   Integer arrays are returned unchanged.  For a `:float64` /
  #   `:float32` array the value stays floating-point (e.g. `1.4` ->
  #   `1.0`); a `NaN` element is passed through as `NaN`, and `-0.0`
  #   keeps its sign.  Masked elements stay masked.  An `:object`
  #   array delegates to each element's `#round`.
  #   @return [CArray] same `data_type` as `self`.
  def round; end

  # @overload frac
  #   Returns a new array of the fractional part of each element:
  #   `self - self.truncated_toward_zero`, so the result keeps the
  #   sign of the input (`1.25` -> `0.25`, `-1.25` -> `-0.25`).  The
  #   result keeps `self`'s `data_type`.
  #
  #   Integer arrays yield all zeros.  For a floating-point array a
  #   `NaN` element is passed through as `NaN`, and `±0.0` keeps its
  #   sign.  Masked elements stay masked.  An `:object` array
  #   delegates to each element's `#frac`.
  #   @return [CArray] same `data_type` as `self`.
  def frac; end

  # @!endgroup
end
