/* ---------------------------------------------------------------------------
 *
 *  carray_call_cfunc.c -- ext-author math-call wrapper API
 *
 *  GENERATED by ext/mk_call_cfunc.rb -- DO NOT EDIT
 *  To modify the template or add a new arity, edit mk_call_cfunc.rb
 *  and regenerate (= make / extconf re-runs the generator).
 *
 *  Provides `ca_call_cfunc_N` (raw arity 1..7) and `ca_call_cfunc_M_N`
 *  (typed dispatcher) used by external CArray gems (carray-gsl, etc.)
 *  to wrap C math functions over CArray operations.
 *
 *  Reentrant variants `ca_call_cfunc_N_r` and `ca_call_cfunc_M_N_r`
 *  (= POSIX `_r` convention, cf. qsort_r / bsearch_r / strtok_r) take
 *  a trailing `void *userdata` argument that is passed through to every
 *  per-cell callback invocation as its last argument.  Use when the
 *  callback needs to share state with the caller (accumulators,
 *  configuration flags, library plan handles, ...) without resorting to
 *  file-static / global plumbing.
 *
 *  Attach-safe: INPUT-only operands (= fsync[k] == '0') never call
 *  ca_attach on the operand or its mask (= alias check + ALLOCV +
 *  ca_xfer_all for non-alias).  OUTPUT operands (= fsync[k] == '1')
 *  use ca_attach + ca_sync (= legitimate per the refined input-only-
 *  operand invariant established in PROPOSAL_EAGER_ELEMENTWISE_NO_ATTACH
 *  and extended in PROPOSAL_EAGER_SLOWPATH_CHUNKING_ARENA).
 *
 *  L0.1 (PROPOSAL_L0_AUTHOR_SURFACE, 2026-06-11): the per-operand acquire
 *  + broadcast check + mask OR + release lifecycle is now factored out
 *  into ext/ca_sweep_engine.{c,h} (ca_sweep_acquire / ca_sweep_release).  This
 *  file keeps the arity-dependent inner loop only.  ABI unchanged.
 *
 *  --------------------------------------------------------------------------- */

#include "carray.h"
#include "ca_sweep_engine.h"
#include <string.h>

VALUE
ca_call_cfunc_1 (void (*func)(void *p0), const char *fsync,
                            VALUE rcx0)
{
  CArray   *cx[1];
  char     *base[1];
  ca_size_t stride[1];
  char     *owned_buf[1];
  int       attached[1];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);

  /* sweep engine: per-operand acquire (alias / xmalloc + ca_xfer_all),
     broadcast shape check, mask OR across INPUTs, mask propagate to
     OUTPUTs.  Lifecycle template lives in ext/ca_sweep_engine.{c,h}. */
  state.n_ops     = 1;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_1";

  ca_sweep_acquire(&state);

  /* inner loop: advance per-cell ptrs and invoke user kernel func */
  {
    char *p[1];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 1; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0]);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 1; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0]);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_2 (void (*func)(void *p0, void *p1), const char *fsync,
                            VALUE rcx0, VALUE rcx1)
{
  CArray   *cx[2];
  char     *base[2];
  ca_size_t stride[2];
  char     *owned_buf[2];
  int       attached[2];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);

  /* sweep engine: per-operand acquire (alias / xmalloc + ca_xfer_all),
     broadcast shape check, mask OR across INPUTs, mask propagate to
     OUTPUTs.  Lifecycle template lives in ext/ca_sweep_engine.{c,h}. */
  state.n_ops     = 2;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_2";

  ca_sweep_acquire(&state);

  /* inner loop: advance per-cell ptrs and invoke user kernel func */
  {
    char *p[2];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 2; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1]);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 2; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1]);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_3 (void (*func)(void *p0, void *p1, void *p2), const char *fsync,
                            VALUE rcx0, VALUE rcx1, VALUE rcx2)
{
  CArray   *cx[3];
  char     *base[3];
  ca_size_t stride[3];
  char     *owned_buf[3];
  int       attached[3];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);

  /* sweep engine: per-operand acquire (alias / xmalloc + ca_xfer_all),
     broadcast shape check, mask OR across INPUTs, mask propagate to
     OUTPUTs.  Lifecycle template lives in ext/ca_sweep_engine.{c,h}. */
  state.n_ops     = 3;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_3";

  ca_sweep_acquire(&state);

  /* inner loop: advance per-cell ptrs and invoke user kernel func */
  {
    char *p[3];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 3; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2]);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 3; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2]);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_4 (void (*func)(void *p0, void *p1, void *p2, void *p3), const char *fsync,
                            VALUE rcx0, VALUE rcx1, VALUE rcx2, VALUE rcx3)
{
  CArray   *cx[4];
  char     *base[4];
  ca_size_t stride[4];
  char     *owned_buf[4];
  int       attached[4];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);
  TypedData_Get_Struct(rcx3, CArray, &carray_data_type, cx[3]);

  /* sweep engine: per-operand acquire (alias / xmalloc + ca_xfer_all),
     broadcast shape check, mask OR across INPUTs, mask propagate to
     OUTPUTs.  Lifecycle template lives in ext/ca_sweep_engine.{c,h}. */
  state.n_ops     = 4;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_4";

  ca_sweep_acquire(&state);

  /* inner loop: advance per-cell ptrs and invoke user kernel func */
  {
    char *p[4];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 4; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2], p[3]);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 4; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2], p[3]);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_5 (void (*func)(void *p0, void *p1, void *p2, void *p3, void *p4), const char *fsync,
                            VALUE rcx0, VALUE rcx1, VALUE rcx2, VALUE rcx3, VALUE rcx4)
{
  CArray   *cx[5];
  char     *base[5];
  ca_size_t stride[5];
  char     *owned_buf[5];
  int       attached[5];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);
  TypedData_Get_Struct(rcx3, CArray, &carray_data_type, cx[3]);
  TypedData_Get_Struct(rcx4, CArray, &carray_data_type, cx[4]);

  /* sweep engine: per-operand acquire (alias / xmalloc + ca_xfer_all),
     broadcast shape check, mask OR across INPUTs, mask propagate to
     OUTPUTs.  Lifecycle template lives in ext/ca_sweep_engine.{c,h}. */
  state.n_ops     = 5;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_5";

  ca_sweep_acquire(&state);

  /* inner loop: advance per-cell ptrs and invoke user kernel func */
  {
    char *p[5];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 5; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2], p[3], p[4]);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 5; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2], p[3], p[4]);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_6 (void (*func)(void *p0, void *p1, void *p2, void *p3, void *p4, void *p5), const char *fsync,
                            VALUE rcx0, VALUE rcx1, VALUE rcx2, VALUE rcx3, VALUE rcx4, VALUE rcx5)
{
  CArray   *cx[6];
  char     *base[6];
  ca_size_t stride[6];
  char     *owned_buf[6];
  int       attached[6];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);
  TypedData_Get_Struct(rcx3, CArray, &carray_data_type, cx[3]);
  TypedData_Get_Struct(rcx4, CArray, &carray_data_type, cx[4]);
  TypedData_Get_Struct(rcx5, CArray, &carray_data_type, cx[5]);

  /* sweep engine: per-operand acquire (alias / xmalloc + ca_xfer_all),
     broadcast shape check, mask OR across INPUTs, mask propagate to
     OUTPUTs.  Lifecycle template lives in ext/ca_sweep_engine.{c,h}. */
  state.n_ops     = 6;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_6";

  ca_sweep_acquire(&state);

  /* inner loop: advance per-cell ptrs and invoke user kernel func */
  {
    char *p[6];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 6; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2], p[3], p[4], p[5]);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 6; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2], p[3], p[4], p[5]);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_7 (void (*func)(void *p0, void *p1, void *p2, void *p3, void *p4, void *p5, void *p6), const char *fsync,
                            VALUE rcx0, VALUE rcx1, VALUE rcx2, VALUE rcx3, VALUE rcx4, VALUE rcx5, VALUE rcx6)
{
  CArray   *cx[7];
  char     *base[7];
  ca_size_t stride[7];
  char     *owned_buf[7];
  int       attached[7];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);
  TypedData_Get_Struct(rcx3, CArray, &carray_data_type, cx[3]);
  TypedData_Get_Struct(rcx4, CArray, &carray_data_type, cx[4]);
  TypedData_Get_Struct(rcx5, CArray, &carray_data_type, cx[5]);
  TypedData_Get_Struct(rcx6, CArray, &carray_data_type, cx[6]);

  /* sweep engine: per-operand acquire (alias / xmalloc + ca_xfer_all),
     broadcast shape check, mask OR across INPUTs, mask propagate to
     OUTPUTs.  Lifecycle template lives in ext/ca_sweep_engine.{c,h}. */
  state.n_ops     = 7;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_7";

  ca_sweep_acquire(&state);

  /* inner loop: advance per-cell ptrs and invoke user kernel func */
  {
    char *p[7];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 7; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2], p[3], p[4], p[5], p[6]);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 7; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2], p[3], p[4], p[5], p[6]);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

/* -------------------------------------------------------------------- */
/* Typed dispatchers: M outputs, N inputs.  Wrap each input readonly to */
/* its declared data_type, allocate output template(s), delegate to raw.    */
/* -------------------------------------------------------------------- */

VALUE
ca_call_cfunc_1_1 (int8_t dty, int8_t dtx1, void (*mathfunc)(void*, void*), volatile VALUE rx1)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));

  if ( dty != dtx1 ) {
    ry = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(1, rx1);
  }

  ca_call_cfunc_2(mathfunc, "10", ry, rx1);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_2 (int8_t dty, int8_t dtx1, int8_t dtx2, void (*mathfunc)(void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));

  if ( dty != dtx1 || dty != dtx2 ) {
    ry = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(2, rx1, rx2);
  }

  ca_call_cfunc_3(mathfunc, "100", ry, rx1, rx2);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_3 (int8_t dty, int8_t dtx1, int8_t dtx2, int8_t dtx3, void (*mathfunc)(void*, void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));

  if ( dty != dtx1 || dty != dtx2 || dty != dtx3 ) {
    ry = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)), rb_ca_wrap_readonly(rx3, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(3, rx1, rx2, rx3);
  }

  ca_call_cfunc_4(mathfunc, "1000", ry, rx1, rx2, rx3);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_4 (int8_t dty, int8_t dtx1, int8_t dtx2, int8_t dtx3, int8_t dtx4, void (*mathfunc)(void*, void*, void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, volatile VALUE rx4)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));
  rx4 = rb_ca_wrap_readonly(rx4, INT2NUM(dtx4));

  if ( dty != dtx1 || dty != dtx2 || dty != dtx3 || dty != dtx4 ) {
    ry = rb_ca_template_n(4, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)), rb_ca_wrap_readonly(rx3, INT2NUM(dty)), rb_ca_wrap_readonly(rx4, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(4, rx1, rx2, rx3, rx4);
  }

  ca_call_cfunc_5(mathfunc, "10000", ry, rx1, rx2, rx3, rx4);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_5 (int8_t dty, int8_t dtx1, int8_t dtx2, int8_t dtx3, int8_t dtx4, int8_t dtx5, void (*mathfunc)(void*, void*, void*, void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, volatile VALUE rx4, volatile VALUE rx5)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));
  rx4 = rb_ca_wrap_readonly(rx4, INT2NUM(dtx4));
  rx5 = rb_ca_wrap_readonly(rx5, INT2NUM(dtx5));

  if ( dty != dtx1 || dty != dtx2 || dty != dtx3 || dty != dtx4 || dty != dtx5 ) {
    ry = rb_ca_template_n(5, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)), rb_ca_wrap_readonly(rx3, INT2NUM(dty)), rb_ca_wrap_readonly(rx4, INT2NUM(dty)), rb_ca_wrap_readonly(rx5, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(5, rx1, rx2, rx3, rx4, rx5);
  }

  ca_call_cfunc_6(mathfunc, "100000", ry, rx1, rx2, rx3, rx4, rx5);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_6 (int8_t dty, int8_t dtx1, int8_t dtx2, int8_t dtx3, int8_t dtx4, int8_t dtx5, int8_t dtx6, void (*mathfunc)(void*, void*, void*, void*, void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, volatile VALUE rx4, volatile VALUE rx5, volatile VALUE rx6)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));
  rx4 = rb_ca_wrap_readonly(rx4, INT2NUM(dtx4));
  rx5 = rb_ca_wrap_readonly(rx5, INT2NUM(dtx5));
  rx6 = rb_ca_wrap_readonly(rx6, INT2NUM(dtx6));

  if ( dty != dtx1 || dty != dtx2 || dty != dtx3 || dty != dtx4 || dty != dtx5 || dty != dtx6 ) {
    ry = rb_ca_template_n(6, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)), rb_ca_wrap_readonly(rx3, INT2NUM(dty)), rb_ca_wrap_readonly(rx4, INT2NUM(dty)), rb_ca_wrap_readonly(rx5, INT2NUM(dty)), rb_ca_wrap_readonly(rx6, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(6, rx1, rx2, rx3, rx4, rx5, rx6);
  }

  ca_call_cfunc_7(mathfunc, "1000000", ry, rx1, rx2, rx3, rx4, rx5, rx6);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_2_1 (int8_t dty1, int8_t dty2, int8_t dtx1, void (*mathfunc)(void*, void*, void*), volatile VALUE rx1)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));

  if ( dty1 != dtx1 ) {
    ry1 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(1, rx1);
  }
  if ( dty2 != dtx1 ) {
    ry2 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(1, rx1);
  }

  ca_call_cfunc_3(mathfunc, "110", ry1, ry2, rx1);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  return rb_ary_new3(2, ry1, ry2);
}

VALUE
ca_call_cfunc_2_2 (int8_t dty1, int8_t dty2, int8_t dtx1, int8_t dtx2, void (*mathfunc)(void*, void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));

  if ( dty1 != dtx1 || dty1 != dtx2 ) {
    ry1 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(2, rx1, rx2);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 ) {
    ry2 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(2, rx1, rx2);
  }

  ca_call_cfunc_4(mathfunc, "1100", ry1, ry2, rx1, rx2);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  return rb_ary_new3(2, ry1, ry2);
}

VALUE
ca_call_cfunc_2_3 (int8_t dty1, int8_t dty2, int8_t dtx1, int8_t dtx2, int8_t dtx3, void (*mathfunc)(void*, void*, void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));

  if ( dty1 != dtx1 || dty1 != dtx2 || dty1 != dtx3 ) {
    ry1 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)), rb_ca_wrap_readonly(rx3, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(3, rx1, rx2, rx3);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 || dty2 != dtx3 ) {
    ry2 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)), rb_ca_wrap_readonly(rx3, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(3, rx1, rx2, rx3);
  }

  ca_call_cfunc_5(mathfunc, "11000", ry1, ry2, rx1, rx2, rx3);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  return rb_ary_new3(2, ry1, ry2);
}

VALUE
ca_call_cfunc_2_4 (int8_t dty1, int8_t dty2, int8_t dtx1, int8_t dtx2, int8_t dtx3, int8_t dtx4, void (*mathfunc)(void*, void*, void*, void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, volatile VALUE rx4)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));
  rx4 = rb_ca_wrap_readonly(rx4, INT2NUM(dtx4));

  if ( dty1 != dtx1 || dty1 != dtx2 || dty1 != dtx3 || dty1 != dtx4 ) {
    ry1 = rb_ca_template_n(4, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)), rb_ca_wrap_readonly(rx3, INT2NUM(dty1)), rb_ca_wrap_readonly(rx4, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(4, rx1, rx2, rx3, rx4);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 || dty2 != dtx3 || dty2 != dtx4 ) {
    ry2 = rb_ca_template_n(4, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)), rb_ca_wrap_readonly(rx3, INT2NUM(dty2)), rb_ca_wrap_readonly(rx4, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(4, rx1, rx2, rx3, rx4);
  }

  ca_call_cfunc_6(mathfunc, "110000", ry1, ry2, rx1, rx2, rx3, rx4);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  return rb_ary_new3(2, ry1, ry2);
}

VALUE
ca_call_cfunc_3_1 (int8_t dty1, int8_t dty2, int8_t dty3, int8_t dtx1, void (*mathfunc)(void*, void*, void*, void*), volatile VALUE rx1)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil, ry3 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));

  if ( dty1 != dtx1 ) {
    ry1 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(1, rx1);
  }
  if ( dty2 != dtx1 ) {
    ry2 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(1, rx1);
  }
  if ( dty3 != dtx1 ) {
    ry3 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty3)));
  } else {
    ry3 = rb_ca_template_n(1, rx1);
  }

  ca_call_cfunc_4(mathfunc, "1110", ry1, ry2, ry3, rx1);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  if ( rb_ca_is_scalar(ry3) ) {
    ry3 = rb_ca_fetch_addr(ry3, 0);
  }
  return rb_ary_new3(3, ry1, ry2, ry3);
}

VALUE
ca_call_cfunc_3_2 (int8_t dty1, int8_t dty2, int8_t dty3, int8_t dtx1, int8_t dtx2, void (*mathfunc)(void*, void*, void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil, ry3 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));

  if ( dty1 != dtx1 || dty1 != dtx2 ) {
    ry1 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(2, rx1, rx2);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 ) {
    ry2 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(2, rx1, rx2);
  }
  if ( dty3 != dtx1 || dty3 != dtx2 ) {
    ry3 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty3)), rb_ca_wrap_readonly(rx2, INT2NUM(dty3)));
  } else {
    ry3 = rb_ca_template_n(2, rx1, rx2);
  }

  ca_call_cfunc_5(mathfunc, "11100", ry1, ry2, ry3, rx1, rx2);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  if ( rb_ca_is_scalar(ry3) ) {
    ry3 = rb_ca_fetch_addr(ry3, 0);
  }
  return rb_ary_new3(3, ry1, ry2, ry3);
}

VALUE
ca_call_cfunc_3_3 (int8_t dty1, int8_t dty2, int8_t dty3, int8_t dtx1, int8_t dtx2, int8_t dtx3, void (*mathfunc)(void*, void*, void*, void*, void*, void*), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil, ry3 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));

  if ( dty1 != dtx1 || dty1 != dtx2 || dty1 != dtx3 ) {
    ry1 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)), rb_ca_wrap_readonly(rx3, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(3, rx1, rx2, rx3);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 || dty2 != dtx3 ) {
    ry2 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)), rb_ca_wrap_readonly(rx3, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(3, rx1, rx2, rx3);
  }
  if ( dty3 != dtx1 || dty3 != dtx2 || dty3 != dtx3 ) {
    ry3 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty3)), rb_ca_wrap_readonly(rx2, INT2NUM(dty3)), rb_ca_wrap_readonly(rx3, INT2NUM(dty3)));
  } else {
    ry3 = rb_ca_template_n(3, rx1, rx2, rx3);
  }

  ca_call_cfunc_6(mathfunc, "111000", ry1, ry2, ry3, rx1, rx2, rx3);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  if ( rb_ca_is_scalar(ry3) ) {
    ry3 = rb_ca_fetch_addr(ry3, 0);
  }
  return rb_ary_new3(3, ry1, ry2, ry3);
}

/* -------------------------------------------------------------------- */
/* Reentrant variants (`_r` suffix, POSIX convention): same as the    */
/* corresponding non-`_r` variant but the callback takes a trailing   */
/* `void *userdata` argument and the outer function takes a trailing  */
/* `void *userdata` parameter forwarded to every per-cell invocation. */
/* -------------------------------------------------------------------- */

VALUE
ca_call_cfunc_1_r (void (*func)(void *p0, void *userdata), const char *fsync,
                              VALUE rcx0,
                              void *userdata)
{
  CArray   *cx[1];
  char     *base[1];
  ca_size_t stride[1];
  char     *owned_buf[1];
  int       attached[1];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);

  /* sweep engine: same lifecycle as ca_call_cfunc_1; the difference is
     the per-cell `func(...)` call has `userdata` as its last argument. */
  state.n_ops     = 1;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_1_r";

  ca_sweep_acquire(&state);

  {
    char *p[1];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 1; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], userdata);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 1; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], userdata);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_2_r (void (*func)(void *p0, void *p1, void *userdata), const char *fsync,
                              VALUE rcx0, VALUE rcx1,
                              void *userdata)
{
  CArray   *cx[2];
  char     *base[2];
  ca_size_t stride[2];
  char     *owned_buf[2];
  int       attached[2];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);

  /* sweep engine: same lifecycle as ca_call_cfunc_2; the difference is
     the per-cell `func(...)` call has `userdata` as its last argument. */
  state.n_ops     = 2;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_2_r";

  ca_sweep_acquire(&state);

  {
    char *p[2];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 2; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], userdata);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 2; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], userdata);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_3_r (void (*func)(void *p0, void *p1, void *p2, void *userdata), const char *fsync,
                              VALUE rcx0, VALUE rcx1, VALUE rcx2,
                              void *userdata)
{
  CArray   *cx[3];
  char     *base[3];
  ca_size_t stride[3];
  char     *owned_buf[3];
  int       attached[3];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);

  /* sweep engine: same lifecycle as ca_call_cfunc_3; the difference is
     the per-cell `func(...)` call has `userdata` as its last argument. */
  state.n_ops     = 3;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_3_r";

  ca_sweep_acquire(&state);

  {
    char *p[3];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 3; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2], userdata);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 3; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2], userdata);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_4_r (void (*func)(void *p0, void *p1, void *p2, void *p3, void *userdata), const char *fsync,
                              VALUE rcx0, VALUE rcx1, VALUE rcx2, VALUE rcx3,
                              void *userdata)
{
  CArray   *cx[4];
  char     *base[4];
  ca_size_t stride[4];
  char     *owned_buf[4];
  int       attached[4];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);
  TypedData_Get_Struct(rcx3, CArray, &carray_data_type, cx[3]);

  /* sweep engine: same lifecycle as ca_call_cfunc_4; the difference is
     the per-cell `func(...)` call has `userdata` as its last argument. */
  state.n_ops     = 4;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_4_r";

  ca_sweep_acquire(&state);

  {
    char *p[4];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 4; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2], p[3], userdata);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 4; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2], p[3], userdata);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_5_r (void (*func)(void *p0, void *p1, void *p2, void *p3, void *p4, void *userdata), const char *fsync,
                              VALUE rcx0, VALUE rcx1, VALUE rcx2, VALUE rcx3, VALUE rcx4,
                              void *userdata)
{
  CArray   *cx[5];
  char     *base[5];
  ca_size_t stride[5];
  char     *owned_buf[5];
  int       attached[5];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);
  TypedData_Get_Struct(rcx3, CArray, &carray_data_type, cx[3]);
  TypedData_Get_Struct(rcx4, CArray, &carray_data_type, cx[4]);

  /* sweep engine: same lifecycle as ca_call_cfunc_5; the difference is
     the per-cell `func(...)` call has `userdata` as its last argument. */
  state.n_ops     = 5;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_5_r";

  ca_sweep_acquire(&state);

  {
    char *p[5];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 5; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2], p[3], p[4], userdata);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 5; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2], p[3], p[4], userdata);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_6_r (void (*func)(void *p0, void *p1, void *p2, void *p3, void *p4, void *p5, void *userdata), const char *fsync,
                              VALUE rcx0, VALUE rcx1, VALUE rcx2, VALUE rcx3, VALUE rcx4, VALUE rcx5,
                              void *userdata)
{
  CArray   *cx[6];
  char     *base[6];
  ca_size_t stride[6];
  char     *owned_buf[6];
  int       attached[6];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);
  TypedData_Get_Struct(rcx3, CArray, &carray_data_type, cx[3]);
  TypedData_Get_Struct(rcx4, CArray, &carray_data_type, cx[4]);
  TypedData_Get_Struct(rcx5, CArray, &carray_data_type, cx[5]);

  /* sweep engine: same lifecycle as ca_call_cfunc_6; the difference is
     the per-cell `func(...)` call has `userdata` as its last argument. */
  state.n_ops     = 6;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_6_r";

  ca_sweep_acquire(&state);

  {
    char *p[6];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 6; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2], p[3], p[4], p[5], userdata);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 6; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2], p[3], p[4], p[5], userdata);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_7_r (void (*func)(void *p0, void *p1, void *p2, void *p3, void *p4, void *p5, void *p6, void *userdata), const char *fsync,
                              VALUE rcx0, VALUE rcx1, VALUE rcx2, VALUE rcx3, VALUE rcx4, VALUE rcx5, VALUE rcx6,
                              void *userdata)
{
  CArray   *cx[7];
  char     *base[7];
  ca_size_t stride[7];
  char     *owned_buf[7];
  int       attached[7];
  ca_sweep_state_t state;
  int k_op;

  TypedData_Get_Struct(rcx0, CArray, &carray_data_type, cx[0]);
  TypedData_Get_Struct(rcx1, CArray, &carray_data_type, cx[1]);
  TypedData_Get_Struct(rcx2, CArray, &carray_data_type, cx[2]);
  TypedData_Get_Struct(rcx3, CArray, &carray_data_type, cx[3]);
  TypedData_Get_Struct(rcx4, CArray, &carray_data_type, cx[4]);
  TypedData_Get_Struct(rcx5, CArray, &carray_data_type, cx[5]);
  TypedData_Get_Struct(rcx6, CArray, &carray_data_type, cx[6]);

  /* sweep engine: same lifecycle as ca_call_cfunc_7; the difference is
     the per-cell `func(...)` call has `userdata` as its last argument. */
  state.n_ops     = 7;
  state.fsync     = fsync;
  state.cx        = cx;
  state.base      = base;
  state.stride    = stride;
  state.owned_buf = owned_buf;
  state.attached  = attached;
  state.no_mask   = 0;
  state.src_label = "ca_call_cfunc_7_r";

  ca_sweep_acquire(&state);

  {
    char *p[7];
    ca_size_t k;
    if ( state.m0 ) {
      for ( k = 0; k < state.n_kernel; k++ ) {
        if ( ! state.m0[k] ) {
          for ( k_op = 0; k_op < 7; k_op++ ) {
            p[k_op] = base[k_op] + k * stride[k_op];
          }
          func(p[0], p[1], p[2], p[3], p[4], p[5], p[6], userdata);
        }
      }
    } else {
      for ( k = 0; k < state.n_kernel; k++ ) {
        for ( k_op = 0; k_op < 7; k_op++ ) {
          p[k_op] = base[k_op] + k * stride[k_op];
        }
        func(p[0], p[1], p[2], p[3], p[4], p[5], p[6], userdata);
      }
    }
  }

  ca_sweep_release(&state);

  return rcx0;
}

VALUE
ca_call_cfunc_1_1_r (int8_t dty, int8_t dtx1, void (*mathfunc)(void*, void*, void *userdata), volatile VALUE rx1, void *userdata)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));

  if ( dty != dtx1 ) {
    ry = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(1, rx1);
  }

  ca_call_cfunc_2_r(mathfunc, "10", ry, rx1, userdata);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_2_r (int8_t dty, int8_t dtx1, int8_t dtx2, void (*mathfunc)(void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, void *userdata)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));

  if ( dty != dtx1 || dty != dtx2 ) {
    ry = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(2, rx1, rx2);
  }

  ca_call_cfunc_3_r(mathfunc, "100", ry, rx1, rx2, userdata);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_3_r (int8_t dty, int8_t dtx1, int8_t dtx2, int8_t dtx3, void (*mathfunc)(void*, void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, void *userdata)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));

  if ( dty != dtx1 || dty != dtx2 || dty != dtx3 ) {
    ry = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)), rb_ca_wrap_readonly(rx3, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(3, rx1, rx2, rx3);
  }

  ca_call_cfunc_4_r(mathfunc, "1000", ry, rx1, rx2, rx3, userdata);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_4_r (int8_t dty, int8_t dtx1, int8_t dtx2, int8_t dtx3, int8_t dtx4, void (*mathfunc)(void*, void*, void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, volatile VALUE rx4, void *userdata)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));
  rx4 = rb_ca_wrap_readonly(rx4, INT2NUM(dtx4));

  if ( dty != dtx1 || dty != dtx2 || dty != dtx3 || dty != dtx4 ) {
    ry = rb_ca_template_n(4, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)), rb_ca_wrap_readonly(rx3, INT2NUM(dty)), rb_ca_wrap_readonly(rx4, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(4, rx1, rx2, rx3, rx4);
  }

  ca_call_cfunc_5_r(mathfunc, "10000", ry, rx1, rx2, rx3, rx4, userdata);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_5_r (int8_t dty, int8_t dtx1, int8_t dtx2, int8_t dtx3, int8_t dtx4, int8_t dtx5, void (*mathfunc)(void*, void*, void*, void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, volatile VALUE rx4, volatile VALUE rx5, void *userdata)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));
  rx4 = rb_ca_wrap_readonly(rx4, INT2NUM(dtx4));
  rx5 = rb_ca_wrap_readonly(rx5, INT2NUM(dtx5));

  if ( dty != dtx1 || dty != dtx2 || dty != dtx3 || dty != dtx4 || dty != dtx5 ) {
    ry = rb_ca_template_n(5, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)), rb_ca_wrap_readonly(rx3, INT2NUM(dty)), rb_ca_wrap_readonly(rx4, INT2NUM(dty)), rb_ca_wrap_readonly(rx5, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(5, rx1, rx2, rx3, rx4, rx5);
  }

  ca_call_cfunc_6_r(mathfunc, "100000", ry, rx1, rx2, rx3, rx4, rx5, userdata);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_1_6_r (int8_t dty, int8_t dtx1, int8_t dtx2, int8_t dtx3, int8_t dtx4, int8_t dtx5, int8_t dtx6, void (*mathfunc)(void*, void*, void*, void*, void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, volatile VALUE rx4, volatile VALUE rx5, volatile VALUE rx6, void *userdata)
{
  volatile VALUE ry = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));
  rx4 = rb_ca_wrap_readonly(rx4, INT2NUM(dtx4));
  rx5 = rb_ca_wrap_readonly(rx5, INT2NUM(dtx5));
  rx6 = rb_ca_wrap_readonly(rx6, INT2NUM(dtx6));

  if ( dty != dtx1 || dty != dtx2 || dty != dtx3 || dty != dtx4 || dty != dtx5 || dty != dtx6 ) {
    ry = rb_ca_template_n(6, rb_ca_wrap_readonly(rx1, INT2NUM(dty)), rb_ca_wrap_readonly(rx2, INT2NUM(dty)), rb_ca_wrap_readonly(rx3, INT2NUM(dty)), rb_ca_wrap_readonly(rx4, INT2NUM(dty)), rb_ca_wrap_readonly(rx5, INT2NUM(dty)), rb_ca_wrap_readonly(rx6, INT2NUM(dty)));
  } else {
    ry = rb_ca_template_n(6, rx1, rx2, rx3, rx4, rx5, rx6);
  }

  ca_call_cfunc_7_r(mathfunc, "1000000", ry, rx1, rx2, rx3, rx4, rx5, rx6, userdata);

  if ( rb_ca_is_scalar(ry) ) {
    ry = rb_ca_fetch_addr(ry, 0);
  }
  return ry;
}

VALUE
ca_call_cfunc_2_1_r (int8_t dty1, int8_t dty2, int8_t dtx1, void (*mathfunc)(void*, void*, void*, void *userdata), volatile VALUE rx1, void *userdata)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));

  if ( dty1 != dtx1 ) {
    ry1 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(1, rx1);
  }
  if ( dty2 != dtx1 ) {
    ry2 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(1, rx1);
  }

  ca_call_cfunc_3_r(mathfunc, "110", ry1, ry2, rx1, userdata);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  return rb_ary_new3(2, ry1, ry2);
}

VALUE
ca_call_cfunc_2_2_r (int8_t dty1, int8_t dty2, int8_t dtx1, int8_t dtx2, void (*mathfunc)(void*, void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, void *userdata)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));

  if ( dty1 != dtx1 || dty1 != dtx2 ) {
    ry1 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(2, rx1, rx2);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 ) {
    ry2 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(2, rx1, rx2);
  }

  ca_call_cfunc_4_r(mathfunc, "1100", ry1, ry2, rx1, rx2, userdata);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  return rb_ary_new3(2, ry1, ry2);
}

VALUE
ca_call_cfunc_2_3_r (int8_t dty1, int8_t dty2, int8_t dtx1, int8_t dtx2, int8_t dtx3, void (*mathfunc)(void*, void*, void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, void *userdata)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));

  if ( dty1 != dtx1 || dty1 != dtx2 || dty1 != dtx3 ) {
    ry1 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)), rb_ca_wrap_readonly(rx3, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(3, rx1, rx2, rx3);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 || dty2 != dtx3 ) {
    ry2 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)), rb_ca_wrap_readonly(rx3, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(3, rx1, rx2, rx3);
  }

  ca_call_cfunc_5_r(mathfunc, "11000", ry1, ry2, rx1, rx2, rx3, userdata);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  return rb_ary_new3(2, ry1, ry2);
}

VALUE
ca_call_cfunc_2_4_r (int8_t dty1, int8_t dty2, int8_t dtx1, int8_t dtx2, int8_t dtx3, int8_t dtx4, void (*mathfunc)(void*, void*, void*, void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, volatile VALUE rx4, void *userdata)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));
  rx4 = rb_ca_wrap_readonly(rx4, INT2NUM(dtx4));

  if ( dty1 != dtx1 || dty1 != dtx2 || dty1 != dtx3 || dty1 != dtx4 ) {
    ry1 = rb_ca_template_n(4, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)), rb_ca_wrap_readonly(rx3, INT2NUM(dty1)), rb_ca_wrap_readonly(rx4, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(4, rx1, rx2, rx3, rx4);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 || dty2 != dtx3 || dty2 != dtx4 ) {
    ry2 = rb_ca_template_n(4, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)), rb_ca_wrap_readonly(rx3, INT2NUM(dty2)), rb_ca_wrap_readonly(rx4, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(4, rx1, rx2, rx3, rx4);
  }

  ca_call_cfunc_6_r(mathfunc, "110000", ry1, ry2, rx1, rx2, rx3, rx4, userdata);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  return rb_ary_new3(2, ry1, ry2);
}

VALUE
ca_call_cfunc_3_1_r (int8_t dty1, int8_t dty2, int8_t dty3, int8_t dtx1, void (*mathfunc)(void*, void*, void*, void*, void *userdata), volatile VALUE rx1, void *userdata)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil, ry3 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));

  if ( dty1 != dtx1 ) {
    ry1 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(1, rx1);
  }
  if ( dty2 != dtx1 ) {
    ry2 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(1, rx1);
  }
  if ( dty3 != dtx1 ) {
    ry3 = rb_ca_template_n(1, rb_ca_wrap_readonly(rx1, INT2NUM(dty3)));
  } else {
    ry3 = rb_ca_template_n(1, rx1);
  }

  ca_call_cfunc_4_r(mathfunc, "1110", ry1, ry2, ry3, rx1, userdata);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  if ( rb_ca_is_scalar(ry3) ) {
    ry3 = rb_ca_fetch_addr(ry3, 0);
  }
  return rb_ary_new3(3, ry1, ry2, ry3);
}

VALUE
ca_call_cfunc_3_2_r (int8_t dty1, int8_t dty2, int8_t dty3, int8_t dtx1, int8_t dtx2, void (*mathfunc)(void*, void*, void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, void *userdata)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil, ry3 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));

  if ( dty1 != dtx1 || dty1 != dtx2 ) {
    ry1 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(2, rx1, rx2);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 ) {
    ry2 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(2, rx1, rx2);
  }
  if ( dty3 != dtx1 || dty3 != dtx2 ) {
    ry3 = rb_ca_template_n(2, rb_ca_wrap_readonly(rx1, INT2NUM(dty3)), rb_ca_wrap_readonly(rx2, INT2NUM(dty3)));
  } else {
    ry3 = rb_ca_template_n(2, rx1, rx2);
  }

  ca_call_cfunc_5_r(mathfunc, "11100", ry1, ry2, ry3, rx1, rx2, userdata);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  if ( rb_ca_is_scalar(ry3) ) {
    ry3 = rb_ca_fetch_addr(ry3, 0);
  }
  return rb_ary_new3(3, ry1, ry2, ry3);
}

VALUE
ca_call_cfunc_3_3_r (int8_t dty1, int8_t dty2, int8_t dty3, int8_t dtx1, int8_t dtx2, int8_t dtx3, void (*mathfunc)(void*, void*, void*, void*, void*, void*, void *userdata), volatile VALUE rx1, volatile VALUE rx2, volatile VALUE rx3, void *userdata)
{
  volatile VALUE ry1 = Qnil, ry2 = Qnil, ry3 = Qnil;

  rx1 = rb_ca_wrap_readonly(rx1, INT2NUM(dtx1));
  rx2 = rb_ca_wrap_readonly(rx2, INT2NUM(dtx2));
  rx3 = rb_ca_wrap_readonly(rx3, INT2NUM(dtx3));

  if ( dty1 != dtx1 || dty1 != dtx2 || dty1 != dtx3 ) {
    ry1 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty1)), rb_ca_wrap_readonly(rx2, INT2NUM(dty1)), rb_ca_wrap_readonly(rx3, INT2NUM(dty1)));
  } else {
    ry1 = rb_ca_template_n(3, rx1, rx2, rx3);
  }
  if ( dty2 != dtx1 || dty2 != dtx2 || dty2 != dtx3 ) {
    ry2 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty2)), rb_ca_wrap_readonly(rx2, INT2NUM(dty2)), rb_ca_wrap_readonly(rx3, INT2NUM(dty2)));
  } else {
    ry2 = rb_ca_template_n(3, rx1, rx2, rx3);
  }
  if ( dty3 != dtx1 || dty3 != dtx2 || dty3 != dtx3 ) {
    ry3 = rb_ca_template_n(3, rb_ca_wrap_readonly(rx1, INT2NUM(dty3)), rb_ca_wrap_readonly(rx2, INT2NUM(dty3)), rb_ca_wrap_readonly(rx3, INT2NUM(dty3)));
  } else {
    ry3 = rb_ca_template_n(3, rx1, rx2, rx3);
  }

  ca_call_cfunc_6_r(mathfunc, "111000", ry1, ry2, ry3, rx1, rx2, rx3, userdata);

  if ( rb_ca_is_scalar(ry1) ) {
    ry1 = rb_ca_fetch_addr(ry1, 0);
  }
  if ( rb_ca_is_scalar(ry2) ) {
    ry2 = rb_ca_fetch_addr(ry2, 0);
  }
  if ( rb_ca_is_scalar(ry3) ) {
    ry3 = rb_ca_fetch_addr(ry3, 0);
  }
  return rb_ary_new3(3, ry1, ry2, ry3);
}

