# Generates ca_pow5_table.h: for each decimal exponent q in [-342, 308], a
# 128-bit approximation of 5^q scaled by a power of two into [2^127, 2^128),
# as the Eisel-Lemire decimal-to-binary64 conversion takes it.
#
# q >= 0:        floor(5^q * 2^k)            (exact while 5^q < 2^128, q <= 55)
# -27 <= q < 0:  ceil(2^k / 5^-q)
# q < -27:       floor(2^k / 5^-q)
# with k chosen so the value has exactly 128 bits.

Q_MIN, Q_MAX = -342, 308
rows = (Q_MIN..Q_MAX).map do |q|
  if q >= 0
    v = 5**q
    v <<= 128 - v.bit_length if v.bit_length < 128
    v >>= v.bit_length - 128 if v.bit_length > 128
  else
    p5 = 5**-q
    k = 127 + p5.bit_length
    v, r = (1 << k).divmod(p5)
    v += 1 if q >= -27 && r != 0
    v >>= v.bit_length - 128 if v.bit_length > 128
    v <<= 128 - v.bit_length if v.bit_length < 128
  end
  raise "bad width at #{q}" unless v.bit_length == 128
  [v >> 64, v & ((1 << 64) - 1)]
end

File.open(File.join(__dir__, "ca_pow5_table.h"), "w") do |f|
  f.puts "/* Generated by mk_pow5_table.rb -- do not edit. */"
  f.puts "#define CA_POW5_Q_MIN (#{Q_MIN})"
  f.puts "#define CA_POW5_Q_MAX #{Q_MAX}"
  f.puts "static const uint64_t ca_pow5_table[#{rows.size * 2}] = {"
  rows.each { |hi, lo| f.puts format("  0x%016xULL, 0x%016xULL,", hi, lo) }
  f.puts "};"
end
